-- GEMAR MENGAJI - TAHAP 20
-- Notifikasi internal guru yang dipicu manual oleh Koordinator.
-- Additive: tidak menghapus/mengubah siswa, nilai, kelompok, absensi, atau rapor.
BEGIN;
SET LOCAL lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS public.internal_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    recipient_teacher_id text,
    sender_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    notification_type text NOT NULL DEFAULT 'attention_score',
    title text NOT NULL,
    message text NOT NULL,
    target_page text NOT NULL DEFAULT 'dashboard',
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    context_key text,
    created_at timestamptz NOT NULL DEFAULT now(),
    seen_at timestamptz,
    read_at timestamptz,
    push_status text NOT NULL DEFAULT 'not_requested'
);

CREATE INDEX IF NOT EXISTS internal_notifications_recipient_created_idx
    ON public.internal_notifications(recipient_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS internal_notifications_context_idx
    ON public.internal_notifications(recipient_user_id, context_key, created_at DESC);
CREATE INDEX IF NOT EXISTS internal_notifications_unseen_idx
    ON public.internal_notifications(recipient_user_id, seen_at)
    WHERE seen_at IS NULL;

ALTER TABLE public.internal_notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS internal_notifications_own_read ON public.internal_notifications;
CREATE POLICY internal_notifications_own_read
ON public.internal_notifications FOR SELECT TO authenticated
USING (recipient_user_id = auth.uid());

-- Penulisan/update dilakukan lewat RPC agar penerima tidak dapat mengubah isi notifikasi.
REVOKE ALL ON public.internal_notifications FROM PUBLIC, anon;
GRANT SELECT ON public.internal_notifications TO authenticated;

CREATE OR REPLACE FUNCTION public.gm_my_notifications(limit_key integer DEFAULT 30)
RETURNS TABLE(
    id bigint,
    notification_type text,
    title text,
    message text,
    target_page text,
    payload jsonb,
    created_at timestamptz,
    seen_at timestamptz,
    read_at timestamptz,
    push_status text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $fn$
    SELECT n.id, n.notification_type, n.title, n.message, n.target_page, n.payload,
           n.created_at, n.seen_at, n.read_at, n.push_status
    FROM public.internal_notifications n
    WHERE n.recipient_user_id = auth.uid()
    ORDER BY n.created_at DESC
    LIMIT LEAST(GREATEST(COALESCE(limit_key,30),1),50);
$fn$;

CREATE OR REPLACE FUNCTION public.gm_mark_notifications_seen()
RETURNS integer
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $fn$
DECLARE changed integer;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Akun diperlukan'; END IF;
    UPDATE public.internal_notifications n
       SET seen_at = COALESCE(n.seen_at, now())
     WHERE n.recipient_user_id = auth.uid()
       AND n.seen_at IS NULL;
    GET DIAGNOSTICS changed = ROW_COUNT;
    RETURN changed;
END
$fn$;

CREATE OR REPLACE FUNCTION public.gm_mark_notification_read(notification_key bigint)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $fn$
DECLARE changed integer;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Akun diperlukan'; END IF;
    UPDATE public.internal_notifications n
       SET seen_at = COALESCE(n.seen_at, now()),
           read_at = COALESCE(n.read_at, now())
     WHERE n.id = notification_key
       AND n.recipient_user_id = auth.uid();
    GET DIAGNOSTICS changed = ROW_COUNT;
    RETURN changed > 0;
END
$fn$;

CREATE OR REPLACE FUNCTION public.gm_send_attention_notification(
    teacher_key text,
    year_key integer DEFAULT NULL,
    period_key text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $fn$
DECLARE
    actor_role text;
    yr integer;
    pr text;
    period_label text;
    teacher_label text;
    student_count integer := 0;
    item_count integer := 0;
    subject_count integer := 0;
    subject_label text;
    recipient record;
    sent_count integer := 0;
    recent_count integer := 0;
    account_count integer := 0;
    context_value text;
    notif_message text;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Akun diperlukan'; END IF;

    SELECT r.role INTO actor_role
    FROM public.user_roles r
    WHERE r.user_id = auth.uid();

    IF actor_role IS DISTINCT FROM 'koordinator' THEN
        RAISE EXCEPTION 'Hanya Koordinator yang dapat mengirim pengingat';
    END IF;

    IF NULLIF(trim(COALESCE(teacher_key,'')),'') IS NULL THEN
        RAISE EXCEPTION 'Guru tidak valid';
    END IF;

    SELECT COALESCE(NULLIF(trim(t.nama_lengkap),''), t.nama)::text
      INTO teacher_label
      FROM public.teachers t
     WHERE t.id::text = teacher_key;
    IF teacher_label IS NULL THEN RAISE EXCEPTION 'Guru tidak ditemukan'; END IF;

    yr := COALESCE(
        year_key,
        EXTRACT(YEAR FROM now() AT TIME ZONE 'Asia/Jakarta')::integer
          - CASE WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') < 7 THEN 1 ELSE 0 END
    );
    pr := COALESCE(period_key,
        CASE
          WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') BETWEEN 7 AND 10 THEN 'pts_ganjil'
          WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') BETWEEN 11 AND 12 THEN 'pas_ganjil'
          WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') BETWEEN 1 AND 3 THEN 'pts_genap'
          ELSE 'pas_genap'
        END
    );
    IF yr NOT BETWEEN 2000 AND 2200 THEN RAISE EXCEPTION 'Tahun ajaran tidak valid'; END IF;
    IF pr NOT IN ('pts_ganjil','pas_ganjil','pts_genap','pas_genap') THEN RAISE EXCEPTION 'Periode tidak valid'; END IF;

    period_label := CASE pr
        WHEN 'pts_ganjil' THEN 'PTS Semester 1'
        WHEN 'pas_ganjil' THEN 'PAS Semester 1'
        WHEN 'pts_genap' THEN 'PTS Semester 2'
        WHEN 'pas_genap' THEN 'PAS Semester 2'
    END;

    WITH issues AS (
        SELECT a.student_id, a.subject
        FROM public.gm_attention_center(yr, pr) a
        WHERE a.issue_type = 'incomplete_score'
          AND a.teacher_id = teacher_key
    )
    SELECT COUNT(DISTINCT i.student_id)::integer,
           COUNT(*)::integer,
           COUNT(DISTINCT i.subject)::integer
      INTO student_count, item_count, subject_count
      FROM issues i;

    IF student_count = 0 THEN
        RETURN jsonb_build_object(
            'status','no_issues','teacher_name',teacher_label,
            'student_count',0,'item_count',0,'sent',0,'recent',0
        );
    END IF;

    WITH subjects AS (
        SELECT DISTINCT a.subject
        FROM public.gm_attention_center(yr, pr) a
        WHERE a.issue_type = 'incomplete_score'
          AND a.teacher_id = teacher_key
    )
    SELECT CASE
        WHEN COUNT(*) > 1 THEN 'Tahsin dan Tahfidz'
        WHEN MAX(subject) = 'tahfidz' THEN 'Tahfidz'
        ELSE 'Tahsin'
    END
    INTO subject_label
    FROM subjects;

    context_value := format('attention_score:%s:%s:%s', yr, pr, teacher_key);
    notif_message := format('%s siswa masih memiliki nilai %s yang perlu dilengkapi. %s.', student_count, subject_label, period_label);

    FOR recipient IN
        SELECT r.user_id
        FROM public.user_roles r
        WHERE r.teacher_id = teacher_key
          AND r.role IN ('guru','koordinator')
          AND r.user_id <> auth.uid()
    LOOP
        account_count := account_count + 1;
        IF EXISTS (
            SELECT 1
            FROM public.internal_notifications n
            WHERE n.recipient_user_id = recipient.user_id
              AND n.context_key = context_value
              AND n.created_at >= now() - interval '10 minutes'
        ) THEN
            recent_count := recent_count + 1;
        ELSE
            INSERT INTO public.internal_notifications(
                recipient_user_id, recipient_teacher_id, sender_user_id,
                notification_type, title, message, target_page, payload,
                context_key, push_status
            ) VALUES (
                recipient.user_id, teacher_key, auth.uid(),
                'attention_score', 'Nilai perlu dilengkapi', notif_message, 'dashboard',
                jsonb_build_object(
                    'year',yr,'period',pr,'teacher_id',teacher_key,
                    'student_count',student_count,'item_count',item_count,
                    'subject',subject_label,'attention_filter','scores'
                ),
                context_value, 'not_requested'
            );
            sent_count := sent_count + 1;
        END IF;
    END LOOP;

    IF account_count = 0 THEN
        RETURN jsonb_build_object(
            'status','no_account','teacher_name',teacher_label,
            'student_count',student_count,'item_count',item_count,
            'sent',0,'recent',0
        );
    END IF;

    RETURN jsonb_build_object(
        'status', CASE WHEN sent_count > 0 THEN 'sent' ELSE 'recent' END,
        'teacher_name', teacher_label,
        'student_count', student_count,
        'item_count', item_count,
        'sent', sent_count,
        'recent', recent_count,
        'accounts', account_count
    );
END
$fn$;

REVOKE ALL ON FUNCTION public.gm_my_notifications(integer) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.gm_mark_notifications_seen() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.gm_mark_notification_read(bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.gm_send_attention_notification(text,integer,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.gm_my_notifications(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gm_mark_notifications_seen() TO authenticated;
GRANT EXECUTE ON FUNCTION public.gm_mark_notification_read(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gm_send_attention_notification(text,integer,text) TO authenticated;

COMMENT ON TABLE public.internal_notifications IS 'Notifikasi internal akun Gemar Mengaji. Web Push memakai status pada record yang sama pada tahap berikutnya.';
COMMENT ON FUNCTION public.gm_send_attention_notification(text,integer,text) IS 'Koordinator mengirim satu pengingat ringkas per guru berdasarkan nilai belum lengkap pada Pusat Perlu Perhatian.';

COMMIT;
NOTIFY pgrst, 'reload schema';
