const fs=require('fs'), path=require('path'), assert=require('assert');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'js/rev46-experience.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/rev46-experience.css'),'utf8');
const pwa=fs.readFileSync(path.join(root,'js/pwa.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const admin=fs.readFileSync(path.join(root,'admin.html'),'utf8');
assert(js.includes("gm-presentasi-cache-v49"));
assert(js.includes("30*24*60*60*1000"));
assert(js.includes("isCurrent?2*60*1000"));
assert(js.includes("reportCacheTtl(year, period)"));
assert(js.includes("gmPresentationTahsinCounts"));
assert(js.includes("gmPresentationTahfidzCounts"));
assert(js.includes("gmPresentationTahsinClassCounts"));
assert(js.includes("gmPresentationTahfidzClassCounts"));
assert(js.includes("presentationGroupColors"));
assert(!js.includes("Capaian dominan:"));
assert(js.includes("maxTicksLimit:compact?6:12"));
assert(js.includes("Data Sudah Ditampilkan"));
assert(css.includes(".gm-target-count-grid"));
assert(css.includes(".gm-attendance-month-strip"));
assert(admin.includes('loader49'));
assert(pwa.includes("BUILD = 'loader49'"));
assert(sw.includes("VERSION = 'loader49'"));
console.log('REV49 presentation cache/chart checks: OK');
