const fs=require('fs'), path=require('path'), assert=require('assert');
const root=path.resolve(__dirname,'..');
const js=fs.readFileSync(path.join(root,'js/rev46-experience.js'),'utf8');
const css=fs.readFileSync(path.join(root,'css/rev46-experience.css'),'utf8');
const sidebar=fs.readFileSync(path.join(root,'js/sidebar.js'),'utf8');
const admin=fs.readFileSync(path.join(root,'admin.html'),'utf8');
const pwa=fs.readFileSync(path.join(root,'js/pwa.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
assert(js.includes('academicYearMonthContexts(startYear)'));
assert(js.includes("gmPresentationTahsinClass"));
assert(js.includes("gmPresentationTahfidzClass"));
assert(js.includes('data-class-target-grade'));
assert(js.includes("type:'bar'"));
assert(js.includes('Juli') || js.includes('monthLabel'));
assert(js.includes('attendanceAcademicSeries'));
assert(js.includes('Bulan yang belum berjalan dibiarkan kosong'));
assert(!js.includes('Persentase target mengikuti perhitungan rapor yang sudah ada. Siswa yang belum dapat dinilai'));
assert(sidebar.includes('sidebar-hover-expanded'));
assert(css.includes('.gm-class-target-grid'));
assert(css.includes('.sidebar-hover-expanded'));
assert(admin.includes('loader49'));
assert(pwa.includes("BUILD = 'loader49'"));
assert(sw.includes("VERSION = 'loader49'"));
console.log('REV48 presentation/sidebar checks: OK');
