[build]
  publish = "public-build"
  command = "node scripts/build-static.cjs"
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "no-cache"
