-- GEMAR MENGAJI - TAHAP 21
-- Fondasi Web Push PWA untuk notifikasi guru.
-- Additive: tidak mengubah siswa, nilai, kelompok, absensi, atau rapor.
BEGIN;
SET LOCAL lock_timeout = '5s';

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    endpoint text NOT NULL UNIQUE,
    p256dh text NOT NULL,
    auth_key text NOT NULL,
    user_agent text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_success_at timestamptz,
    last_error_at timestamptz
);

CREATE INDEX IF NOT EXISTS push_subscriptions_user_active_idx
    ON public.push_subscriptions(user_id, active);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.push_subscriptions FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.gm_register_push_subscription(
    endpoint_key text,
    p256dh_key text,
    auth_key_value text,
    user_agent_key text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $fn$
DECLARE subscription_id bigint;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Akun diperlukan'; END IF;
    IF NULLIF(trim(COALESCE(endpoint_key,'')),'') IS NULL OR length(endpoint_key) > 4096 THEN
        RAISE EXCEPTION 'Endpoint push tidak valid';
    END IF;
    IF NULLIF(trim(COALESCE(p256dh_key,'')),'') IS NULL OR NULLIF(trim(COALESCE(auth_key_value,'')),'') IS NULL THEN
        RAISE EXCEPTION 'Kunci push tidak lengkap';
    END IF;

    INSERT INTO public.push_subscriptions(user_id, endpoint, p256dh, auth_key, user_agent, active, updated_at)
    VALUES (auth.uid(), endpoint_key, p256dh_key, auth_key_value, left(COALESCE(user_agent_key,''),500), true, now())
    ON CONFLICT (endpoint) DO UPDATE
       SET user_id = auth.uid(),
           p256dh = EXCLUDED.p256dh,
           auth_key = EXCLUDED.auth_key,
           user_agent = EXCLUDED.user_agent,
           active = true,
           updated_at = now(),
           last_error_at = NULL
    RETURNING id INTO subscription_id;

    RETURN subscription_id;
END
$fn$;

CREATE OR REPLACE FUNCTION public.gm_remove_push_subscription(endpoint_key text)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $fn$
DECLARE changed integer;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Akun diperlukan'; END IF;
    UPDATE public.push_subscriptions p
       SET active = false, updated_at = now()
     WHERE p.user_id = auth.uid()
       AND p.endpoint = endpoint_key
       AND p.active = true;
    GET DIAGNOSTICS changed = ROW_COUNT;
    RETURN changed > 0;
END
$fn$;

CREATE OR REPLACE FUNCTION public.gm_my_push_status()
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $fn$
    SELECT COUNT(*)::integer
    FROM public.push_subscriptions p
    WHERE p.user_id = auth.uid()
      AND p.active = true;
$fn$;

-- Perbarui fungsi pengiriman internal agar mengembalikan ID notifikasi yang baru dibuat.
-- ID ini kemudian dipakai Edge Function untuk mengirim Web Push dengan isi yang sama.
CREATE OR REPLACE FUNCTION public.gm_send_attention_notification(
    teacher_key text,
    year_key integer DEFAULT NULL,
    period_key text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $fn$
DECLARE
    actor_role text;
    yr integer;
    pr text;
    period_label text;
    teacher_label text;
    student_count integer := 0;
    item_count integer := 0;
    subject_count integer := 0;
    subject_label text;
    recipient record;
    sent_count integer := 0;
    recent_count integer := 0;
    account_count integer := 0;
    context_value text;
    notif_message text;
    inserted_id bigint;
    notification_ids bigint[] := ARRAY[]::bigint[];
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Akun diperlukan'; END IF;

    SELECT r.role INTO actor_role
    FROM public.user_roles r
    WHERE r.user_id = auth.uid();

    IF actor_role IS DISTINCT FROM 'koordinator' THEN
        RAISE EXCEPTION 'Hanya Koordinator yang dapat mengirim pengingat';
    END IF;

    IF NULLIF(trim(COALESCE(teacher_key,'')),'') IS NULL THEN
        RAISE EXCEPTION 'Guru tidak valid';
    END IF;

    SELECT COALESCE(NULLIF(trim(t.nama_lengkap),''), t.nama)::text
      INTO teacher_label
      FROM public.teachers t
     WHERE t.id::text = teacher_key;
    IF teacher_label IS NULL THEN RAISE EXCEPTION 'Guru tidak ditemukan'; END IF;

    yr := COALESCE(
        year_key,
        EXTRACT(YEAR FROM now() AT TIME ZONE 'Asia/Jakarta')::integer
          - CASE WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') < 7 THEN 1 ELSE 0 END
    );
    pr := COALESCE(period_key,
        CASE
          WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') BETWEEN 7 AND 10 THEN 'pts_ganjil'
          WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') BETWEEN 11 AND 12 THEN 'pas_ganjil'
          WHEN EXTRACT(MONTH FROM now() AT TIME ZONE 'Asia/Jakarta') BETWEEN 1 AND 3 THEN 'pts_genap'
          ELSE 'pas_genap'
        END
    );
    IF yr NOT BETWEEN 2000 AND 2200 THEN RAISE EXCEPTION 'Tahun ajaran tidak valid'; END IF;
    IF pr NOT IN ('pts_ganjil','pas_ganjil','pts_genap','pas_genap') THEN RAISE EXCEPTION 'Periode tidak valid'; END IF;

    period_label := CASE pr
        WHEN 'pts_ganjil' THEN 'PTS Semester 1'
        WHEN 'pas_ganjil' THEN 'PAS Semester 1'
        WHEN 'pts_genap' THEN 'PTS Semester 2'
        WHEN 'pas_genap' THEN 'PAS Semester 2'
    END;

    WITH issues AS (
        SELECT a.student_id, a.subject
        FROM public.gm_attention_center(yr, pr) a
        WHERE a.issue_type = 'incomplete_score'
          AND a.teacher_id = teacher_key
    )
    SELECT COUNT(DISTINCT i.student_id)::integer,
           COUNT(*)::integer,
           COUNT(DISTINCT i.subject)::integer
      INTO student_count, item_count, subject_count
      FROM issues i;

    IF student_count = 0 THEN
        RETURN jsonb_build_object(
            'status','no_issues','teacher_name',teacher_label,
            'student_count',0,'item_count',0,'sent',0,'recent',0,
            'notification_ids','[]'::jsonb
        );
    END IF;

    WITH subjects AS (
        SELECT DISTINCT a.subject
        FROM public.gm_attention_center(yr, pr) a
        WHERE a.issue_type = 'incomplete_score'
          AND a.teacher_id = teacher_key
    )
    SELECT CASE
        WHEN COUNT(*) > 1 THEN 'Tahsin dan Tahfidz'
        WHEN MAX(subject) = 'tahfidz' THEN 'Tahfidz'
        ELSE 'Tahsin'
    END
    INTO subject_label
    FROM subjects;

    context_value := format('attention_score:%s:%s:%s', yr, pr, teacher_key);
    notif_message := format('%s siswa masih memiliki nilai %s yang perlu dilengkapi. %s.', student_count, subject_label, period_label);

    FOR recipient IN
        SELECT r.user_id
        FROM public.user_roles r
        WHERE r.teacher_id = teacher_key
          AND r.role IN ('guru','koordinator')
          AND r.user_id <> auth.uid()
    LOOP
        account_count := account_count + 1;
        IF EXISTS (
            SELECT 1
            FROM public.internal_notifications n
            WHERE n.recipient_user_id = recipient.user_id
              AND n.context_key = context_value
              AND n.created_at >= now() - interval '10 minutes'
        ) THEN
            recent_count := recent_count + 1;
        ELSE
            INSERT INTO public.internal_notifications(
                recipient_user_id, recipient_teacher_id, sender_user_id,
                notification_type, title, message, target_page, payload,
                context_key, push_status
            ) VALUES (
                recipient.user_id, teacher_key, auth.uid(),
                'attention_score', 'Nilai perlu dilengkapi', notif_message, 'dashboard',
                jsonb_build_object(
                    'year',yr,'period',pr,'teacher_id',teacher_key,
                    'student_count',student_count,'item_count',item_count,
                    'subject',subject_label,'attention_filter','scores'
                ),
                context_value, 'pending'
            ) RETURNING id INTO inserted_id;
            notification_ids := array_append(notification_ids, inserted_id);
            sent_count := sent_count + 1;
        END IF;
    END LOOP;

    IF account_count = 0 THEN
        RETURN jsonb_build_object(
            'status','no_account','teacher_name',teacher_label,
            'student_count',student_count,'item_count',item_count,
            'sent',0,'recent',0,'notification_ids','[]'::jsonb
        );
    END IF;

    RETURN jsonb_build_object(
        'status', CASE WHEN sent_count > 0 THEN 'sent' ELSE 'recent' END,
        'teacher_name', teacher_label,
        'student_count', student_count,
        'item_count', item_count,
        'sent', sent_count,
        'recent', recent_count,
        'accounts', account_count,
        'notification_ids', to_jsonb(notification_ids)
    );
END
$fn$;

REVOKE ALL ON FUNCTION public.gm_register_push_subscription(text,text,text,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.gm_remove_push_subscription(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.gm_my_push_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.gm_register_push_subscription(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gm_remove_push_subscription(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.gm_my_push_status() TO authenticated;

COMMENT ON TABLE public.push_subscriptions IS 'Subscription Web Push per akun/perangkat untuk PWA Gemar Mengaji.';
COMMIT;
